on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.18.0"
      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build
        env:
          # VITE_BEARER_TOKEN: ${{ secrets.VITE_BEARER_TOKEN }}
          VITE_BEARER_TOKEN: ${{ env.VITE_BEARER_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.HUGGY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
